PART3/CHAPTER5/01/complete/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('edit/', views.edit, name='edit'),
    path('<int:pk>/', views.detail, name='detail'),
]

PART3/CHAPTER5/01/complete/config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import static
from . import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('timeline.urls')),
    path('accounts/email/', RedirectView.as_view(pattern_name='timeline:index')),
    path('accounts/inactive/', RedirectView.as_view(pattern_name='timeline:index')),
    path('accounts/password/change/', RedirectView.as_view(pattern_name='timeline:index')),
    path('accounts/confirm-email/', RedirectView.as_view(pattern_name='timeline:index')),
    re_path(r'^accounts/confirm-email/[^/]+/', RedirectView.as_view(pattern_name='timeline:index'), kwargs=None),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PART3/CHAPTER5/01/complete/timeline/urls.py
from django.urls import path
from . import views

app_name = 'timeline'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('like/', views.like, name='like'),
]

PART3/CHAPTER5/01/complete/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill

class CustomUser(AbstractUser):
    description = models.TextField(verbose_name='プロフィール', null=True, blank=True)
    photo = models.ImageField(verbose_name='写真', blank=True, null=True, upload_to='images/')
    thumbnail = ImageSpecField(source='photo',
                               processors=[ResizeToFill(256, 256)],
                               format='JPEG',
                               options={'quality': 60})


    class Meta:
        verbose_name_plural = 'CustomUser'

PART3/CHAPTER5/01/complete/timeline/models.py
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit

class Post(models.Model):
	author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
	text = models.TextField(verbose_name='本文')
	photo = models.ImageField(verbose_name='写真', blank=True, null=True, upload_to='images/')
	post_photo = ImageSpecField(source='photo',processors=[ResizeToFit(1080, 1080)],format='JPEG',options={'quality':60})
	created_at = models.DateTimeField(auto_now_add=True, blank=True)


	def get_like(self):
		likes = Like.objects.filter(post=self)
		return [like.user for like in likes]


class Like(models.Model):
	user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
	post = models.ForeignKey('Post', on_delete=models.CASCADE)

	class Meta:
		unique_together = ('user', 'post')

PART3/CHAPTER5/01/complete/accounts/forms.py
from django import forms
from .models import CustomUser

class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = CustomUser
        fields = ('username','description','photo')
        help_texts = {
            'username': None,
        }

PART3/CHAPTER5/01/complete/timeline/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('text', 'photo')

PART3/CHAPTER5/01/complete/accounts/views.py
from .models import CustomUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .forms import ProfileForm
from django.contrib.messages.views import SuccessMessageMixin

class ProfileEdit(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = CustomUser
    form_class = ProfileForm
    template_name = 'account/edit.html'
    success_url = '/accounts/edit/'
    success_message = 'プロフィールを更新しました。'

    def get_object(self):
        return self.request.user

class ProfileDetail(LoginRequiredMixin, generic.DetailView):
    model = CustomUser
    template_name = 'account/detail.html'

edit = ProfileEdit.as_view()
detail = ProfileDetail.as_view()

PART3/CHAPTER5/01/complete/timeline/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .models import Post, Like
from django.http.response import JsonResponse

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'index.html'
    paginate_by = 10

    def get_queryset(self):
        posts = Post.objects.order_by('-created_at')
        return posts

class CreateView(LoginRequiredMixin, generic.CreateView):
    form_class = PostForm
    success_url = reverse_lazy('timeline:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        messages.success(self.request, '投稿が完了しました。')
        return super(CreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, '投稿が失敗しました。')
        return redirect('timeline:index')

class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy('timeline:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == request.user:
            messages.success(self.request, '削除しました。')
            return super().delete(request, *args, **kwargs)

class LikeView(LoginRequiredMixin, generic.View):
    model = Like

    def post(self, request):
        post_id = request.POST.get('id')
        post = Post.objects.get(id=post_id)
        like = Like(user=self.request.user,post=post)
        like.save()
        like_count = Like.objects.filter(post=post).count()
        data = {'message': 'ほめました',
                'like_count': like_count}
        return JsonResponse(data)

index = IndexView.as_view()
create = CreateView.as_view()
delete = DeleteView.as_view()
like = LikeView.as_view()

PART3/CHAPTER5/01/complete/timeline/templates/base.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-info fixed-top">
        <a class="navbar-brand" href="{% url 'timeline:index' %}">POSII</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'timeline:index' %}">タイムライン</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:edit' %}">プロフィール</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">ユーザー登録</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="starter-template">
            {% if messages %}
            <div class="w-100">
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            {% block contents %}{% endblock %}
        </div>
    </main>
    <!-- /.container -->
    <p class="mt-5 mb-3 text-muted text-center ">&copy; 2021 POSII</p>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
</body>
<script>
$.ajaxSetup({
  beforeSend: function (xhr, settings) {
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
          var cookie = jQuery.trim(cookies[i]);
          if (cookie.substring(0, name.length + 1) == (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
      xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    }
  }
});
$(document).on("click", ".post-like", function () {
  var id = $(this).data('id');
  $.ajax({
    type: "post",
    url: "/like/",
    data: {
      id: id,
      csrfmiddlewaretoken: $("#csrfmiddlewaretoken").val()
    },
    success: function (data) {
      $("#post-like-" + id).removeClass("post-like text-info").addClass("post-liked disabled text-secondary");
      var like_count = data["like_count"]
      $("#like-count-" + id).html(like_count);
      alert(data["message"])
    }
  });
});
</script>
</html>

PART3/CHAPTER5/01/complete/timeline/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}トップページ | POSII{% endblock %}
{% block contents %}
<div class="card mb-5 text-left">
  <div class="card-body">
    <div class="row">
      <div class="col-2">
        <img src="{% if user.thumbnail %}{{ user.thumbnail.url }}{% else %}{% static 'images/no_photo.png' %}{% endif %}" class="rounded-circle post-photo">
      </div>
      <div class="col-10">
        <form method="post" action="{% url 'timeline:create' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <textarea class="form-control" id="exampleFormControlTextarea1"  name="text" rows="3" placeholder="例：XXさん、バグをなおしてくれてありがとうございます！"></textarea>
          </div>
          <div class="form-group mt-1">
            <label for="file">画像アップロード</label>
            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="photo">
          </div>
          <button class="btn btn-info btn-block" type="submit">ほめる</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% for post in object_list %}
<div class="card mb-5 text-left">
  <div class="card-body">
    <div class="row">
      <div class="col-1">
        <a href="{% url 'accounts:detail' post.author.id %}"><img src="{% if post.author.thumbnail %}{{ post.author.thumbnail.url }}{% else %}{% static 'images/no_photo.png' %}{% endif %}" class="rounded-circle profile-post-photo"></a>
      </div>
      <div class="col-10 ml-3">
        <a href="{% url 'accounts:detail' post.author.id %}" class="text-secondary">{{ post.author }}</a><br>
        <small class="text-muted">{{ post.created_at | date:"n月j日 H時i分" }}</small>
      </div>
    </div>
    <p class="card-text mt-2">{{ post.text | linebreaks }}</p>
    <button class="btn btn-link p-0 {% if user in post.get_like %}disabled post-liked text-secondary{% else %}post-like text-info{% endif %}" id="post-like-{{ post.id }}" data-id="{{ post.id }}">
        ほめる
    </button>
    <span class="badge badge-info" id="like-count-{{ post.id }}">{% if post.get_like %}{{ post.get_like | length }}{% endif %}</span>
    {% if post.author.id == user.id %}
    <form method="post" action="{% url 'timeline:delete' post.id %}" class="d-inline">
      {% csrf_token %}
      <button class="btn btn-link text-info p-0 ml-3" type="submit" onclick='return confirm("この投稿を本当に削除しますか？");'>
        削除
      </button>
    </form>
    {% endif %}
  </div>
  {% if post.post_photo %}
  <img class="card-img-bottom" src="{{ post.post_photo.url }}" alt="Card image cap">
  {% endif %}
</div>
{% endfor %}

<nav>
  <ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link text-info" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">&laquo;</a>
    </li>
  {% else %}
    <li class="page-item disabled"><span class="page-link">
      &laquo;</span></a>
    </li>
  {% endif %}
  {% for i in page_obj.paginator.page_range %}
  {% if page_obj.number == i %}
    <li class="page-item disabled"><span class="page-link">{{ i }}</span></li>
  {% else %}
    <li class="page-item"><a class="page-link text-info" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link text-info" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <span class="page-link">&raquo;</span>
    </li>
  {% endif %}
  </ul>
</nav>
{% endblock %}